routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::Routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('clientes', 'ClienteController');
    Route::resource('infoClientes', 'InfoClienteController');
    Route::resource('central_users', 'CentralUserController');
    Route::get('/datatablecentral_users', 'DatatableController@centralusertable')->name('datatable.central_users');
    Route::resource('logs', 'LogController');
    Route::resource('permisos', 'PermisoController');
    Route::get('/datatablepermisos', 'DatatableController@permisostable')->name('datatable.permisos');
    Route::resource('roles', 'RolesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('orgs', 'OrgController');
    Route::resource('estacionamientos', 'EstacionamientoController');
    Route::get('/datatableestacionamiento', 'DatatableController@estacionamientotable')->name('datatable.estacionamiento');
    Route::resource('tipoTickets', 'TipoTicketController');
    Route::resource('tickets', 'TicketController');
    Route::resource('factura', 'FacturaController');
    Route::resource('tipoPagos', 'TipoPagoController');
    Route::resource('tipoPensions', 'TipoPensionController');
    Route::resource('formaPagos', 'FormaPagoController');
    Route::resource('imgIngresos', 'ImgIngresoController');
    Route::resource('ingresos', 'IngresoController');
    Route::resource('bancoCollects', 'BancoCollectController');
    Route::resource('empresaCollects', 'EmpresaCollectController');
    Route::resource('gerentes', 'GerenteController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('diarioingreso', 'DiarioIngresoController');
    Route::resource('firmas', 'FirmaController');
    Route::get('/xml/{id}', 'FacturaController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'FacturaController@downloadPDF')->name('pdf');
    Route::get('/pdfcertificado/{id}', 'FacturaController@downloadPDFcertificado')->name('pdfcertificado');
    Route::get('/img/{id}', 'TicketController@DownImg')->name('img');
    Route::post('/generar/', 'FacturaController@create')->name('generar');
    Route::post('/buscar/facturas', 'FacturaController@busqueda')->name('busqueda');
    Route::post('/email', 'FacturaController@enviarEmail')->name('email');
    Route::post('/actualiza/{id}', 'TicketController@actualiza')->name('no_est');
    Route::post('/tickets/timbrado/', 'FacturaController@timbrado')->name('timbrar');
    Route::get('/tickets/validar/{id}', 'TicketController@valido')->name('valido');
    Route::post('/tickets/rechazo/{id}', 'TicketController@rechazo')->name('rechazo');
    Route::get('/rechazados', 'TicketController@list_rechazo')->name('list_rechazo');
    Route::post('dashboard', 'DashboardController@AjaxRequest')->name('dashboard');
    Route::get('/graficas/{id}', 'EstacionamientoController@graficas')->name('graficas');
    Route::get('/ingresos/rechazados', 'IngresoController@Frechazos')->name('ingresos.rechazo');
    Route::get('/facturas/pi', 'FacturaController@pi')->name('pi');
    Route::get('/orgs/cambio/{id}', 'OrgController@cambio')->name('cambio');
    Route::get('/fichas/validar/{id}', 'IngresoController@Fvalidos')->name('valido_ficha');
    Route::post('/fichas/rechazo/{id}', 'IngresoController@Frechazos')->name('rechazo_ficha');
    Route::get('/calendario', 'IngresoController@calendario')->name('calendar');
    //pensiones
    Route::get('/contp/{id}', 'PensionController@downloadContPdf')->name('contp');
    Route::get('/scontp/{id}', 'PensionController@downloadSContPdf')->name('scontp');
    Route::get('/ccontp/{id}', 'PensionController@downloadComprobantedomPdf')->name('ccontp');
    Route::get('/ine/{id}', 'PensionController@downloadIne')->name('ine');
    Route::get('/licencia/{id}', 'PensionController@downloadLic')->name('licencia');
    Route::get('/tarjetaC/{id}', 'PensionController@downloadTarC')->name('tarjetaC');
    Route::get('/compPago/{id}', 'PagoController@downloadcompPago')->name('compPago');
    Route::get('/xmlPen/{id}', 'FacturaPensionController@downloadpenXML')->name('xmlPen');
    Route::get('/pdfPen/{id}', 'FacturaPensionController@downloadpenPdf')->name('pdfPen');
    Route::get('/facturaPensions/rechazo/{id}', 'FacturaPensionController@rechazo')->name('rechazopension');
    Route::get('/facturaPensions/valido/{id}', 'FacturaPensionController@valido')->name('validopension');
    Route::resource('reportepensions', 'ReportePensionController');
    Route::post('reportepensions', 'ReportePensionController@pagosMesAplicados')->name('pagosMesAplicados');
    Route::post('reportepensionsActivas', 'ReportePensionController@ReporteActivos')->name('ReporteActivos');
    Route::post('reportepensionsInActivas', 'ReportePensionController@ReporteInActivos')->name('ReporteInActivos');
    Route::resource('cargacarso', 'CargaCarsoController');
    Route::resource('rdi', 'RDIController');
    //publico en general
    Route::resource('publico-general', 'PublicGeneralController');
    Route::resource('convertidorxml', 'conversorxml');
    Route::view('buscador-tickets', 'tickets.buscador')->name('buscador-tickets');
});



Route::resource('pagos', 'PagoController');
Route::resource('operacionDiarias', 'OperacionDiariaController');
Route::resource('pensions', 'PensionController');


Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('facturaPensions', 'FacturaPensionController');

Route::resource('facturaPensions', 'FacturaPensionController');

Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('asignacionTarjetas', 'AsignacionTarjetaController');

Route::resource('catCfdis', 'catCfdiController');

Route::resource('catMetodoPagos', 'catMetodoPagoController');

Route::resource('catBancos', 'catBancosController');

Route::resource('penalizacions', 'PenalizacionController');

Route::resource('estacionamientoPensions', 'EstacionamientoPensionController');

Route::resource('gerentePensions', 'GerentePensionController');

Route::resource('asignacionTarjetas', 'AsignacionTarjetaController');

Route::resource('catConceptos', 'CatConceptoController');


Route::resource('categoriaTickets', 'CategoriaTicketController');

Route::resource('estatusTickets', 'EstatusTicketController');

Route::resource('nivelesTickets', 'NivelesTicketController');

Route::resource('ticketsTickets', 'TicketsTicketController');

Route::resource('tIncidenciaTickets', 'TIncidenciaTicketController');

app/Http/Controllers/FacturaPensionController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Response;
use App\Models\catCfdi;
use App\Funciones\TimbrarPension;
use App\Models\Pension;
use Illuminate\Http\Request;
use App\Models\catMetodoPago;
use App\Models\FacturaPension;
use App\Http\Controllers\AppBaseController;
use App\Repositories\FacturaPensionRepository;
use App\Http\Requests\CreateFacturaPensionRequest;
use App\Http\Requests\UpdateFacturaPensionRequest;
use CfdiUtils\Validate\Cfdi33\RecepcionPagos\UsoCfdi;
use Illuminate\Support\Facades\DB;

class FacturaPensionController extends AppBaseController
{
    /** @var  FacturaPensionRepository */
    private $facturaPensionRepository;

    public function __construct(FacturaPensionRepository $facturaPensionRepo)
    {
        $this->facturaPensionRepository = $facturaPensionRepo;
    }

    /**
     * Display a listing of the FacturaPension.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        //$facturaPensions = $this->facturaPensionRepository->all();

        $facturaPensions = DB::connection('mysql2')->table('facturaPensiones')
            ->join('pensionesDet', 'facturaPensiones.id_pen', '=', 'pensionesDet.id')
            ->select('facturaPensiones.*', 'pensionesDet.id as id_pen')
            ->get();
        //dd($facturaPensions);

        return view('factura_pensions.index')
            ->with('facturaPensions', $facturaPensions);
    }

    /**
     * Show the form for creating a new FacturaPension.
     *
     * @return Response
     */
    public function create()
    {
        $pensiones = Pension::all();
        $usocfdis = catCfdi::all();
        $metodos =  catMetodoPago::all();
        //dd($metodos);
        return view('factura_pensions.create')->with('pensiones', $pensiones)->with('cfdis', $usocfdis)->with('metodos', $metodos);
    }

    /**
     * Store a newly created FacturaPension in storage.
     *
     * @param CreateFacturaPensionRequest $request
     *
     * @return Response
     */
    public function store(CreateFacturaPensionRequest $request)
    {
        $input = $request->all();

        $xml = '';
        $pdf = '';

        $xml = request()->file('XML');
        if ($xml != null) {
            $datacont = $xml->get();
            $nombre_contrato = $xml->getBasename();
            $cont = file_get_contents($xml);
            //$contdata = base64_encode($cont);
            $input['XML'] = $cont;
            //$contrato = $this->pensionRepository->create($input);
        }

        $pdf = request()->file('PDF');
        if ($pdf != null) {
            $datascont = $pdf->get();
            $nombre_scontrato = $pdf->getBasename();
            $scont = file_get_contents($pdf);
            $scontdata = base64_encode($scont);
            $input['PDF'] = $scontdata;
            //$contrato = $this->pensionRepository->create($input);
        }

        $facturaPension = $this->facturaPensionRepository->create($input);

        flash('Message')->success('Factura actualizada.');

        return redirect(route('facturaPensions.index'));
    }

    /**
     * Display the specified FacturaPension.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            flash('Message')->error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        return view('factura_pensions.show')->with('facturaPension', $facturaPension);
    }

    /**
     * Show the form for editing the specified FacturaPension.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            flash('Message')->error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        $pensiones = Pension::all();
        $usocfdis = catCfdi::all();
        $metodos =  catMetodoPago::all();

        return view('factura_pensions.edit')->with('facturaPension', $facturaPension)->with('pensiones', $pensiones)
            ->with('cfdis', $usocfdis)->with('metodos', $metodos);
    }

    /**
     * Update the specified FacturaPension in storage.
     *
     * @param int $id
     * @param UpdateFacturaPensionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFacturaPensionRequest $request)
    {
        $input = request()->all();
        $facturaPension = facturaPension::find($id);

        if (empty($facturaPension)) {
            flash('Message')->error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        if ($input['id_pen']) {
            $facturaPension->id_pen = $input['id_pen'];
        }

        if ($input['serie']) {
            $facturaPension->serie = $input['serie'];
        }

        if ($input['folio']) {
            $facturaPension->folio = $input['folio'];
        }

        if ($input['fecha_timbrado']) {
            $facturaPension->fecha_timbrado = $input['fecha_timbrado'];
        }

        if ($input['uuid']) {
            $facturaPension->uuid = $input['uuid'];
        }

        if ($input['subtotal_factura']) {
            $facturaPension->subtotal_factura = $input['subtotal_factura'];
        }

        if ($input['iva_factura']) {
            $facturaPension->iva_factura = $input['iva_factura'];
        }

        if ($input['total_factura']) {
            $facturaPension->total_factura = $input['total_factura'];
        }

        if ($input['id_usoCFDI']) {
            $facturaPension->id_usoCFDI = $input['id_usoCFDI'];
        }

        if ($input['id_metodoPago']) {
            $facturaPension->id_metodoPago = $input['id_metodoPago'];
        }

        $xml = '';
        $pdf = '';

        $xml = request()->file('XML');
        if ($xml != null) {
            $datacont = $xml->get();
            $nombre_contrato = $xml->getBasename();
            $cont = file_get_contents($xml);
            //$contdata = base64_encode($cont);
            $facturaPension->XML = $cont;
            //$contrato = $this->pensionRepository->create($input);
        }

        $pdf = request()->file('PDF');
        if ($pdf != null) {
            $datacontd = $pdf->get();
            $nombre_contratod = $pdf->getBasename();
            $contd = file_get_contents($pdf);
            $contdatad = base64_encode($pdf);
            //dd($contdatad);
            $facturaPension->PDF = $contdatad;
            //$contrato = $this->pensionRepository->create($input);
        }

        $facturaPension->save();

        flash('Message')->success('Factura actualizado.');

        return redirect(route('facturaPensions.index'));
    }

    /**
     * Remove the specified FacturaPension from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $facturaPension = $this->facturaPensionRepository->find($id);

        if (empty($facturaPension)) {
            flash('Message')->error('Factura Pension not found');

            return redirect(route('facturaPensions.index'));
        }

        $this->facturaPensionRepository->delete($id);

        flash('Message')->success('Factura eliminada.');

        return redirect(route('facturaPensions.index'));
    }

    public function downloadpenPdf($id)
    {
        $pdf = FacturaPension::find($id);
        $archivo = $pdf->PDF;
        $decoded = base64_decode($archivo);
        $path = "pdfs/" . $pdf->id . ".pdf";
        file_put_contents($path, $decoded);
        header("Content-disposition: attachment; filename=contrato-fact$pdf->id.pdf");
        header("Content-type: application/pdf");
        readfile($path);
        unlink($path);
    }

    public function downloadpenXML($id)
    {
        //$id = \request()->request;
        //dd($id);
        $xml = FacturaPension::find($id);
        $archivo = $xml->XML;
        $path = "xml_down/" . $xml->id . ".xml";
        //dd($uuid);
        file_put_contents($path, $archivo);
        header("Content-disposition: attachment; filename=fact$xml->id.xml");
        header("Content-type: application/xml");
        readfile($path);
        unlink($path);

        //flash('Message')->success('Factura descargada');

        //return redirect(route('facturas.index'));
    }

    public function rechazo($id)
    {

        $query = FacturaPension::findOrFail($id);
        $estatus = $query->estatus;

        $query->estatus = '3';
        $query->save();

        flash('Message')->success('Factura rechazada');

        return redirect(route('facturaPensions.index'));
    }

    public function valido($id)
    {
        $validar = facturaPension::find($id);
        //dd($validar);

        if ($validar->estatus == 1) {
            flash('Message')->error('Ticket timbrado previamente');
            return redirect(route('facturaPensions.index'));
        }

        $timbrar = new TimbrarPension();
        $timbrar->Factura($id, $validar->id_pen);

        return redirect(route('facturaPensions.index'));
    }
}

resources/views/factura_pensions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Nueva factura</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {!! Form::open(['route' => 'facturaPensions.store', 'enctype' => 'multipart/form-data']) !!}

                @include('factura_pensions.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/factura_pensions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Nuevo pago</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {!! Form::model($facturaPension, ['route' => ['facturaPensions.update', $facturaPension->id], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                @include('factura_pensions.fieldsedit')

                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/factura_pensions/fields.blade.php
<!-- Id Pen Field -->
<div class="form-group col-sm-12">
    {!! Form::label('id_pen', 'Pensión:') !!}
    <select class="browser-default custom-select" name="id_pen">
        <option value="" disabled selected>Escoja una opción</option>
        @foreach($pensiones as $pension)
            <option value="{{$pension->id}}">{{$pension->noTarjeta}}</option>
        @endforeach
    </select>
</div>

<!-- Serie Field -->
{{-- <div class="form-group col-sm-12">
    {!! Form::label('serie', 'Serie:') !!}
    {!! Form::text('serie', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Folio Field -->
<div class="form-group col-sm-12">
    {!! Form::label('folio', 'Folio:') !!}
    {!! Form::text('folio', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div> --}}

<!-- Fecha Timbrado Field -->
<div class="form-group col-sm-12">
    {!! Form::label('fecha_timbrado', 'Fecha Timbrado:') !!}
    {!! Form::date('fecha_timbrado', null, ['class' => 'form-control','id'=>'fecha_timbrado']) !!}
</div>

@push('scripts')
    <script type="text/javascript">
        $('#fecha_timbrado').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false
        })
    </script>
@endpush

<!-- Uuid Field -->
{{-- <div class="form-group col-sm-12">
    {!! Form::label('uuid', 'Uuid:') !!}
    {!! Form::text('uuid', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Subtotal Factura Field -->
<div class="form-group col-sm-12">
    {!! Form::label('subtotal_factura', 'Subtotal Factura:') !!}
    {!! Form::number('subtotal_factura', null, ['class' => 'form-control']) !!}
</div>

<!-- Iva Factura Field -->
<div class="form-group col-sm-12">
    {!! Form::label('iva_factura', 'Iva Factura:') !!}
    {!! Form::number('iva_factura', null, ['class' => 'form-control']) !!}
</div> --}}

<!-- Total Factura Field -->
<div class="form-group col-sm-12">
    {!! Form::label('total_factura', 'Total Factura:') !!}
    {!! Form::number('total_factura', null, ['class' => 'form-control']) !!}
</div>

<!-- Xml Field -->
{{-- <div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('XML', 'Xml:') !!}
    <div class="file-field">
        <div class="float-left btn btn-primary btn-sm">
            <span>Cargar xml</span>
            <input type="file" name="XML" id="foto"
                   accept="application/xml">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" name="XML"
                   id="foto" accept="application/xml" type="text"
                   placeholder="Cargar xml">
        </div>
    </div>
</div>

<!-- Pdf Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('PDF', 'Pdf:') !!}
    <div class="file-field">
        <div class="float-left btn btn-primary btn-sm">
            <span>Cargar pdf</span>
            <input type="file" name="PDF" id="foto"
                   accept="application/pdf">
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" name="PDF"
                   id="foto" accept="application/pdf" type="text"
                   placeholder="Cargar pdf">
        </div>
    </div>
</div> --}}

<!-- Estatus Field -->
    {!! Form::hidden('estatus', 2, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}

<!-- Id Usocfdi Field -->
<div class="form-group col-sm-12">
    {!! Form::label('id_usoCFDI', 'Uso cfdi:') !!}
    <select class="browser-default custom-select" name="id_usoCFDI">
        <option value="" disabled selected>Escoja una opción</option>
        @foreach($cfdis as $cfdi)
            <option value="{{$cfdi->id}}">{{$cfdi->claveSat}} / {{$cfdi->descricion}}</option>
        @endforeach
    </select>
</div>
{{--
<!-- Id Metodopago Field -->
<div class="form-group col-sm-12">
    {!! Form::label('id_metodoPago', 'Metodo pago:') !!}
    <select class="browser-default custom-select" name="id_metodoPago">
        <option value="" disabled selected>Escoja una opción</option>
        @foreach($metodos as $metodo)
            <option value="{{$metodo->id}}">{{$metodo->clave}}/{{$metodo->Descripcion}}</option>
        @endforeach
    </select>
</div> --}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enviar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('facturaPensions.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/factura_pensions/index.blade.php
@extends('layouts.app')

@section('content')
     <section class="content">
        <div class="card card-cascade wilder">
            <!-- Card image -->
            <div class="view view-cascade gradient-card-header default-color">
                <!-- Title -->
                <h3 class="card-header-title">Facturas activas</h3>
            </div>
        </div>
        <hr>
        @include('layouts.errors')
        @include('flash::message')
        <div class="row">
            <div class="col-8">
                <button type="button" class="btn btn-default btn-lg">
                    Facturas encontrados: <span class="counter badge badge-danger ml-4"></span>
                </button>
            </div>
            <div class="col-4 text-right">
                <a type="button" class="btn btn-dark btn-rounded" href="{{ route('facturaPensions.create') }}">
                    Añadir
                </a>
            </div>
        </div>
        <br>
        @include('factura_pensions.table')
    </section>
@endsection

resources/views/factura_pensions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Factura Pension
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('factura_pensions.show_fields')
                    <a href="{{ route('facturaPensions.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/factura_pensions/table.blade.php
<div class="table-responsive">
    <table class="table" id="dtBasicExample">
        <thead>
            <tr>
                <th>Pension</th>
                <th>Serie</th>
                <th>Folio</th>
                <th>Fecha Timbrado</th>
                <th>UUID</th>
                <th>Subtotal Factura</th>
                <th>Iva Factura</th>
                <th>Total Factura</th>
                <th>Xml</th>
                <th>Pdf</th>
                <th style="margin-right: 0px;">Estatus</th>
                <!-- <th>Uso cfdi</th>
                <th>Metodo pago</th> -->
                <th style="margin-left: 100px;">Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($facturaPensions as $facturaPension)
                <tr>
                    <td>{{ $facturaPension->id_pen }}</td>
                    <td>
                        @if ($facturaPension->serie)
                            {{ $facturaPension->serie }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->folio)
                            {{ $facturaPension->folio }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->fecha_timbrado)
                            {{ $facturaPension->fecha_timbrado }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->uuid)
                            {{ $facturaPension->uuid }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->subtotal_factura)
                            {{ $facturaPension->subtotal_factura }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->iva_factura)
                            {{ $facturaPension->iva_factura }}
                        @else
                            En espera
                        @endif
                    </td>
                    <td>{{ $facturaPension->total_factura }}</td>
                    <td>
                        @if ($facturaPension->XML)
                            <a href="{!! route('xmlPen', [$facturaPension->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                    class="fas fa-download"></i></a>
                        @else
                            Sin archivo
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->PDF)
                            <a href="{!! route('pdfPen', [$facturaPension->id]) !!}" class='btn-floating btn-sm btn-blue-grey'><i
                                    class="fas fa-download"></i></a>
                        @else
                            Sin archivo
                        @endif
                    </td>
                    <td>
                        @if ($facturaPension->estatus == 1)
                            Timbrada
                        @elseif($facturaPension->estatus == 2)
                            <div class="row">
                                <div class="col-6">
                                    <a type="button" class="btn-floating btn-sm success-color" href="{{route('validopension',$facturaPension->id)}}" id="btn-one"><i
                                            class="far fa-check-circle"></i></a>
                                </div>
                                <div class="col-6">
                                    <a type="button" class="btn-floating btn-sm danger-color" href="{{route('rechazopension',$facturaPension->id)}}" id="btn-one"><i
                                            class="far fa-times-circle"></i></a>
                                </div>
                            </div>
                        @else
                            Rechazada
                        @endif
                    </td>
                    {{-- <td>{{ $facturaPension->id_usoCFDI }}</td>
                    <td>{{ $facturaPension->id_metodoPago }}</td> --}}
                    <td>
                        {!! Form::open(['route' => ['facturaPensions.destroy', $facturaPension->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <!--<a href="{{ route('facturaPensions.show', [$facturaPension->id]) }}"
                           class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>-->
                            <a href="{{ route('facturaPensions.edit', [$facturaPension->id]) }}"
                                class='btn btn-default btn-sm'>Editar</a>
                            {{-- {!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!} --}}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>