routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::Routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('clientes', 'ClienteController');
    Route::resource('infoClientes', 'InfoClienteController');
    Route::resource('central_users', 'CentralUserController');
    Route::get('/datatablecentral_users', 'DatatableController@centralusertable')->name('datatable.central_users');
    Route::resource('logs', 'LogController');
    Route::resource('permisos', 'PermisoController');
    Route::get('/datatablepermisos', 'DatatableController@permisostable')->name('datatable.permisos');
    Route::resource('roles', 'RolesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('orgs', 'OrgController');
    Route::resource('estacionamientos', 'EstacionamientoController');
    Route::get('/datatableestacionamiento', 'DatatableController@estacionamientotable')->name('datatable.estacionamiento');
    Route::resource('tipoTickets', 'TipoTicketController');
    Route::resource('tickets', 'TicketController');
    Route::resource('factura', 'FacturaController');
    Route::resource('tipoPagos', 'TipoPagoController');
    Route::resource('tipoPensions', 'TipoPensionController');
    Route::resource('formaPagos', 'FormaPagoController');
    Route::resource('imgIngresos', 'ImgIngresoController');
    Route::resource('ingresos', 'IngresoController');
    Route::resource('bancoCollects', 'BancoCollectController');
    Route::resource('empresaCollects', 'EmpresaCollectController');
    Route::resource('gerentes', 'GerenteController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('diarioingreso', 'DiarioIngresoController');
    Route::resource('firmas', 'FirmaController');
    Route::get('/xml/{id}', 'FacturaController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'FacturaController@downloadPDF')->name('pdf');
    Route::get('/pdfcertificado/{id}', 'FacturaController@downloadPDFcertificado')->name('pdfcertificado');
    Route::get('/img/{id}', 'TicketController@DownImg')->name('img');
    Route::post('/generar/', 'FacturaController@create')->name('generar');
    Route::post('/buscar/facturas', 'FacturaController@busqueda')->name('busqueda');
    Route::post('/email', 'FacturaController@enviarEmail')->name('email');
    Route::post('/actualiza/{id}', 'TicketController@actualiza')->name('no_est');
    Route::post('/tickets/timbrado/', 'FacturaController@timbrado')->name('timbrar');
    Route::get('/tickets/validar/{id}', 'TicketController@valido')->name('valido');
    Route::post('/tickets/rechazo/{id}', 'TicketController@rechazo')->name('rechazo');
    Route::get('/rechazados', 'TicketController@list_rechazo')->name('list_rechazo');
    Route::post('dashboard', 'DashboardController@AjaxRequest')->name('dashboard');
    Route::get('/graficas/{id}', 'EstacionamientoController@graficas')->name('graficas');
    Route::get('/ingresos/rechazados', 'IngresoController@Frechazos')->name('ingresos.rechazo');
    Route::get('/facturas/pi', 'FacturaController@pi')->name('pi');
    Route::get('/orgs/cambio/{id}', 'OrgController@cambio')->name('cambio');
    Route::get('/fichas/validar/{id}', 'IngresoController@Fvalidos')->name('valido_ficha');
    Route::post('/fichas/rechazo/{id}', 'IngresoController@Frechazos')->name('rechazo_ficha');
    Route::get('/calendario', 'IngresoController@calendario')->name('calendar');
    //pensiones
    Route::get('/contp/{id}', 'PensionController@downloadContPdf')->name('contp');
    Route::get('/scontp/{id}', 'PensionController@downloadSContPdf')->name('scontp');
    Route::get('/ccontp/{id}', 'PensionController@downloadComprobantedomPdf')->name('ccontp');
    Route::get('/ine/{id}', 'PensionController@downloadIne')->name('ine');
    Route::get('/licencia/{id}', 'PensionController@downloadLic')->name('licencia');
    Route::get('/tarjetaC/{id}', 'PensionController@downloadTarC')->name('tarjetaC');
    Route::get('/compPago/{id}', 'PagoController@downloadcompPago')->name('compPago');
    Route::get('/xmlPen/{id}', 'FacturaPensionController@downloadpenXML')->name('xmlPen');
    Route::get('/pdfPen/{id}', 'FacturaPensionController@downloadpenPdf')->name('pdfPen');
    Route::get('/facturaPensions/rechazo/{id}', 'FacturaPensionController@rechazo')->name('rechazopension');
    Route::get('/facturaPensions/valido/{id}', 'FacturaPensionController@valido')->name('validopension');
    Route::resource('reportepensions', 'ReportePensionController');
    Route::post('reportepensions', 'ReportePensionController@pagosMesAplicados')->name('pagosMesAplicados');
    Route::post('reportepensionsActivas', 'ReportePensionController@ReporteActivos')->name('ReporteActivos');
    Route::post('reportepensionsInActivas', 'ReportePensionController@ReporteInActivos')->name('ReporteInActivos');
    Route::resource('cargacarso', 'CargaCarsoController');
    Route::resource('rdi', 'RDIController');
    //publico en general
    Route::resource('publico-general', 'PublicGeneralController');
    Route::resource('convertidorxml', 'conversorxml');
    Route::view('buscador-tickets', 'tickets.buscador')->name('buscador-tickets');
});



Route::resource('pagos', 'PagoController');
Route::resource('operacionDiarias', 'OperacionDiariaController');
Route::resource('pensions', 'PensionController');


Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('facturaPensions', 'FacturaPensionController');

Route::resource('facturaPensions', 'FacturaPensionController');

Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('asignacionTarjetas', 'AsignacionTarjetaController');

Route::resource('catCfdis', 'catCfdiController');

Route::resource('catMetodoPagos', 'catMetodoPagoController');

Route::resource('catBancos', 'catBancosController');

Route::resource('penalizacions', 'PenalizacionController');

Route::resource('estacionamientoPensions', 'EstacionamientoPensionController');

Route::resource('gerentePensions', 'GerentePensionController');

Route::resource('asignacionTarjetas', 'AsignacionTarjetaController');

Route::resource('catConceptos', 'CatConceptoController');


Route::resource('categoriaTickets', 'CategoriaTicketController');

Route::resource('estatusTickets', 'EstatusTicketController');

Route::resource('nivelesTickets', 'NivelesTicketController');

Route::resource('ticketsTickets', 'TicketsTicketController');

Route::resource('tIncidenciaTickets', 'TIncidenciaTicketController');

app/Models/TicketsTicket.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TicketsTicket
 * @package App\Models
 * @version March 29, 2022, 1:18 am CST
 *
 * @property \App\Models\Categorium $idCategoria
 * @property \App\Models\Estatus $idEstatus
 * @property \App\Models\Nivele $idNivel
 * @property \App\Models\TipoIncidencium $idTipo
 * @property string $nombre_ticket
 * @property string $descripcion
 * @property integer $id_proyecto
 * @property integer $id_tipo
 * @property integer $id_asignacion
 * @property integer $id_categoria
 * @property integer $id_nivel
 * @property integer $id_estatus
 * @property integer $id_usuario
 */
class TicketsTicket extends Model
{
    use SoftDeletes;

    public $table = 'tickets';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    public $connection = "mysql3";

    public $fillable = [
        'nombre_ticket',
        'descripcion',
        'id_proyecto',
        'id_tipo',
        'id_asignacion',
        'id_categoria',
        'id_nivel',
        'id_estatus',
        'id_usuario'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id_ticket' => 'integer',
        'nombre_ticket' => 'string',
        'descripcion' => 'string',
        'id_proyecto' => 'integer',
        'id_tipo' => 'integer',
        'id_asignacion' => 'integer',
        'id_categoria' => 'integer',
        'id_nivel' => 'integer',
        'id_estatus' => 'integer',
        'id_usuario' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre_ticket' => 'nullable|string|max:100',
        'descripcion' => 'nullable|string',
        'id_proyecto' => 'nullable|integer',
        'id_tipo' => 'nullable|integer',
        'id_asignacion' => 'nullable',
        'id_categoria' => 'nullable|integer',
        'id_nivel' => 'nullable|integer',
        'id_estatus' => 'nullable|integer',
        'id_usuario' => 'nullable',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idCategoria()
    {
        return $this->belongsTo(\App\Models\Categorium::class, 'id_categoria');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idEstatus()
    {
        return $this->belongsTo(\App\Models\Estatus::class, 'id_estatus');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idNivel()
    {
        return $this->belongsTo(\App\Models\Nivele::class, 'id_nivel');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function idTipo()
    {
        return $this->belongsTo(\App\Models\TipoIncidencium::class, 'id_tipo');
    }
}

app/Http/Controllers/TicketsTicketController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTicketsTicketRequest;
use App\Http\Requests\UpdateTicketsTicketRequest;
use App\Repositories\TicketsTicketRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TicketsTicketController extends AppBaseController
{
    /** @var  TicketsTicketRepository */
    private $ticketsTicketRepository;

    public function __construct(TicketsTicketRepository $ticketsTicketRepo)
    {
        $this->ticketsTicketRepository = $ticketsTicketRepo;
    }

    /**
     * Display a listing of the TicketsTicket.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $ticketsTickets = $this->ticketsTicketRepository->all();

        return view('tickets_tickets.index')
            ->with('ticketsTickets', $ticketsTickets);
    }

    /**
     * Show the form for creating a new TicketsTicket.
     *
     * @return Response
     */
    public function create()
    {
        return view('tickets_tickets.create');
    }

    /**
     * Store a newly created TicketsTicket in storage.
     *
     * @param CreateTicketsTicketRequest $request
     *
     * @return Response
     */
    public function store(CreateTicketsTicketRequest $request)
    {
        $input = $request->all();

        $ticketsTicket = $this->ticketsTicketRepository->create($input);

        flash('Message')->success('Tickets Ticket saved successfully.');

        return redirect(route('ticketsTickets.index'));
    }

    /**
     * Display the specified TicketsTicket.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ticketsTicket = $this->ticketsTicketRepository->find($id);

        if (empty($ticketsTicket)) {
            flash('Message')->error('Tickets Ticket not found');

            return redirect(route('ticketsTickets.index'));
        }

        return view('tickets_tickets.show')->with('ticketsTicket', $ticketsTicket);
    }

    /**
     * Show the form for editing the specified TicketsTicket.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ticketsTicket = $this->ticketsTicketRepository->find($id);

        if (empty($ticketsTicket)) {
            flash('Message')->error('Tickets Ticket not found');

            return redirect(route('ticketsTickets.index'));
        }

        return view('tickets_tickets.edit')->with('ticketsTicket', $ticketsTicket);
    }

    /**
     * Update the specified TicketsTicket in storage.
     *
     * @param int $id
     * @param UpdateTicketsTicketRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTicketsTicketRequest $request)
    {
        $ticketsTicket = $this->ticketsTicketRepository->find($id);

        if (empty($ticketsTicket)) {
            flash('Message')->error('Tickets Ticket not found');

            return redirect(route('ticketsTickets.index'));
        }

        $ticketsTicket = $this->ticketsTicketRepository->update($request->all(), $id);

        flash('Message')->success('Tickets Ticket updated successfully.');

        return redirect(route('ticketsTickets.index'));
    }

    /**
     * Remove the specified TicketsTicket from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ticketsTicket = $this->ticketsTicketRepository->find($id);

        if (empty($ticketsTicket)) {
            flash('Message')->error('Tickets Ticket not found');

            return redirect(route('ticketsTickets.index'));
        }

        $this->ticketsTicketRepository->delete($id);

        flash('Message')->success('Tickets Ticket deleted successfully.');

        return redirect(route('ticketsTickets.index'));
    }
}

resources/views/tickets_tickets/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tickets Ticket
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ticketsTickets.store']) !!}

                        @include('tickets_tickets.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tickets_tickets/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tickets Ticket
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ticketsTicket, ['route' => ['ticketsTickets.update', $ticketsTicket->id], 'method' => 'patch']) !!}

                        @include('tickets_tickets.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/tickets_tickets/fields.blade.php
<!-- Nombre Ticket Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre_ticket', 'Nombre Ticket:') !!}
    {!! Form::text('nombre_ticket', null, ['class' => 'form-control','maxlength' => 100,'maxlength' => 100]) !!}
</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    {!! Form::textarea('descripcion', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Proyecto Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_proyecto', 'Id Proyecto:') !!}
    {!! Form::number('id_proyecto', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Tipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_tipo', 'Id Tipo:') !!}
    {!! Form::number('id_tipo', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Asignacion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_asignacion', 'Id Asignacion:') !!}
    {!! Form::number('id_asignacion', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Categoria Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_categoria', 'Id Categoria:') !!}
    {!! Form::number('id_categoria', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Nivel Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_nivel', 'Id Nivel:') !!}
    {!! Form::number('id_nivel', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Estatus Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_estatus', 'Id Estatus:') !!}
    {!! Form::number('id_estatus', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Usuario Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_usuario', 'Id Usuario:') !!}
    {!! Form::number('id_usuario', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('ticketsTickets.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/tickets_tickets/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Tickets Tickets</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('ticketsTickets.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('tickets_tickets.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/tickets_tickets/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tickets Ticket
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('tickets_tickets.show_fields')
                    <a href="{{ route('ticketsTickets.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tickets_tickets/show_fields.blade.php
<!-- Nombre Ticket Field -->
<div class="form-group">
    {!! Form::label('nombre_ticket', 'Nombre Ticket:') !!}
    <p>{{ $ticketsTicket->nombre_ticket }}</p>
</div>

<!-- Descripcion Field -->
<div class="form-group">
    {!! Form::label('descripcion', 'Descripcion:') !!}
    <p>{{ $ticketsTicket->descripcion }}</p>
</div>

<!-- Id Proyecto Field -->
<div class="form-group">
    {!! Form::label('id_proyecto', 'Id Proyecto:') !!}
    <p>{{ $ticketsTicket->id_proyecto }}</p>
</div>

<!-- Id Tipo Field -->
<div class="form-group">
    {!! Form::label('id_tipo', 'Id Tipo:') !!}
    <p>{{ $ticketsTicket->id_tipo }}</p>
</div>

<!-- Id Asignacion Field -->
<div class="form-group">
    {!! Form::label('id_asignacion', 'Id Asignacion:') !!}
    <p>{{ $ticketsTicket->id_asignacion }}</p>
</div>

<!-- Id Categoria Field -->
<div class="form-group">
    {!! Form::label('id_categoria', 'Id Categoria:') !!}
    <p>{{ $ticketsTicket->id_categoria }}</p>
</div>

<!-- Id Nivel Field -->
<div class="form-group">
    {!! Form::label('id_nivel', 'Id Nivel:') !!}
    <p>{{ $ticketsTicket->id_nivel }}</p>
</div>

<!-- Id Estatus Field -->
<div class="form-group">
    {!! Form::label('id_estatus', 'Id Estatus:') !!}
    <p>{{ $ticketsTicket->id_estatus }}</p>
</div>

<!-- Id Usuario Field -->
<div class="form-group">
    {!! Form::label('id_usuario', 'Id Usuario:') !!}
    <p>{{ $ticketsTicket->id_usuario }}</p>
</div>

resources/views/tickets_tickets/table.blade.php
<div class="table-responsive">
    <table class="table" id="ticketsTickets-table">
        <thead>
            <tr>
                <th>Nombre Ticket</th>
        <th>Descripcion</th>
        <th>Id Proyecto</th>
        <th>Id Tipo</th>
        <th>Id Asignacion</th>
        <th>Id Categoria</th>
        <th>Id Nivel</th>
        <th>Id Estatus</th>
        <th>Id Usuario</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($ticketsTickets as $ticketsTicket)
            <tr>
                <td>{{ $ticketsTicket->nombre_ticket }}</td>
            <td>{{ $ticketsTicket->descripcion }}</td>
            <td>{{ $ticketsTicket->id_proyecto }}</td>
            <td>{{ $ticketsTicket->id_tipo }}</td>
            <td>{{ $ticketsTicket->id_asignacion }}</td>
            <td>{{ $ticketsTicket->id_categoria }}</td>
            <td>{{ $ticketsTicket->id_nivel }}</td>
            <td>{{ $ticketsTicket->id_estatus }}</td>
            <td>{{ $ticketsTicket->id_usuario }}</td>
                <td>
                    {!! Form::open(['route' => ['ticketsTickets.destroy', $ticketsTicket->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('ticketsTickets.show', [$ticketsTicket->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('ticketsTickets.edit', [$ticketsTicket->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>